openapi: 3.0.1
info:
  title: finx-celta-tm-product-service
  version: '1.0'
  description:  TM Product service
servers:
  - url: 'https://finx-celta-api-dev.fincuro.in'
paths:
  /v1/products:
    get:
      tags:
        - Product
      summary: List Products
      operationId: listProducts
      parameters:
        - name: pageSize
          in: query
          required: true
          schema:
            type: integer
        - name: pageToken
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []
  /v1/products/{productVersionId}:
    get:
      tags:
        - Product
      summary: Search Individual
      operationId: searchIndividual
      parameters:
        - name: productVersionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductVersionDetailsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []
  
components:
  schemas:
    ProductResponse:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              displayName:
                type: string
              isInternal:
                type: boolean
              currentVersionId:
                type: string
        previousPageToken:
          type: string
        nextPageToken:
          type: string
    ProductVersionDetailsResponse:
      type: object
      properties:
        id:
          type: string
        displayName:
          type: string
        description:
          type: string
        summay:
          type: string
        params:
          type: array
          items:
            type: string
        productId:
          type: string
        tside:
          type: string
        supportedDenominations:
          type: array
          items:
            type: string
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT